### PR TITLE
ERD and  schema

### PR DESCRIPTION
**Pull request by ayushkumar2808**
ER diagram - 
Screenshot 2023-09-23 at 9 43 44 AM

Link - https://drive.google.com/file/d/18ujmF79ih-WgwpBSlFJo5ux7uWQ86U57/view?usp=sharing

Schema table
Screenshot 2023-09-25 at 12 05 18 PM

Link - https://lucid.app/lucidchart/fb4660c1-4182-43c4-8e9f-f5d677b06c52/edit?invitationId=inv_22860acd-670a-4560-9487-95fedb1614e2

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
1. Add loom video explanation for your diagrams. Explain each and every entities with all connections made. 
2. In schema diagram, properly connect the foreign keys to appropriate primary keys table. (with exact pointing to foreign key with primary key)

**Comment by ayushkumar2808** [comment]
here is the link for the loom video-
https://www.loom.com/share/01d91816004f467a9fd3f01ae91bd4df?sid=ec4d4b80-793a-43ec-812b-68d7baf18763

I have also also updated the schema table.

**Comment by Kalvium-Program** [comment]
Idea explanation is fine,
But missing proper explanation to transaction table, about - transaction type, also ERD is missing with transferred_to attribute,
Loan should be connected to account's table, (ie loan table should have account_id as foreign key)

**Comment by PRASANNAPATHI** [comment]
Idea explanation is fine,
But missing proper explanation to transaction table, about - transaction type & processing, also ERD is missing with transferred_to attribute and related explanation.
Loan should be connected to account's table, (ie loan table should have account_id as foreign key)

**Comment by ayushkumar2808** [comment]
Screenshot 2023-09-25 at 6 17 50 PM
Screenshot 2023-09-25 at 6 18 10 PM

**Comment by Kalvium-Program** [comment]
Yeah, looks good.

you can merge it now.

**Comment by PRASANNAPATHI** [comment]
Yeah, Looks good.

You can merge it now.

**Pull request merged**
