### PR TITLE
Advanced SQL queries, Constructors and Destructors

### PR DESCRIPTION
**Pull request by ayushkumar2808**
### DBMS

Topic - Advanced SQL queries

Video 1 - https://www.loom.com/share/1e779bb560734b0e928ef8e9fc4ed3a4?sid=ac45c5c9-9d7f-4a84-b7eb-02fa42f5cc8b

Video 2 - https://www.loom.com/share/cca489ed8a054289b2f73abfb1db8651?sid=9c5fc817-2a15-4146-8027-0723d53b0fa9

### OOPS

Topics:

1. Dynamic memory Allocation

Video link - https://www.loom.com/share/33cdde9950d84b5c95aba3717bb43db3?sid=45ac3dd4-85e0-4afd-9279-814cfeb78808

2. Constructors and destructors
Video link - https://www.loom.com/share/366e89746b7445e6be603bb127347782?sid=58aa04fd-9fca-4eb1-9553-69a29c160723

Video link - https://www.loom.com/share/139d30579e554f688e3c3bd20e97eac3?sid=4aabfd90-7f4a-401f-85d8-3607884cdb64

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Hey @ayushkumar2808 ,

For DBMS

Your explanation, commands and execution are good and sufficient for this concept.
But you need to write atleast 3 commands, but only 2 are there.

Please you can merge it for DBMS (Advanced SQL Queries).

If you want to score fully, please submit the required no. of commands as mentioned above.

**Comment by ayushkumar2808** [comment]
Hey @PRASANNAPATHI ,
this query retrieves data for a specific user, including their main accounts (the first SELECT part) and their subaccounts with the calculated total balance (the second SELECT part). The results are combined using UNION, and the "totalBalance" column is used to distinguish between main and subaccounts, with NULL indicating main accounts and the calculated total balance for subaccounts. The query is parameterized with a placeholder (question mark) for the user ID, which should be provided when executing the query.

**Comment by PRASANNAPATHI** [comment]
Yes @ayushkumar2808, its fine now.

Please merge it now.

**Comment by Tharun-kailash** [comment]
For OOP,
Self viva is clear and satisfactory.
Pl go ahead and merge this PR!

**Pull request merged**
