### PR TITLE
This pointer

### PR DESCRIPTION
**Pull request by ayushkumar2808**
OOPs:-

1. this pointer
2. interface
Loom video - https://www.loom.com/share/26ee7421ac9c4afa9cec9855b5507c86?sid=a037a5ce-2bf8-42b8-b7de-ddaf75ea9f70

DBMS

1. DML commands
Loom video - https://www.loom.com/share/cd4befd37d8045c7b2b5c27d9336855e?sid=953683e0-c525-41a9-8e75-429a83306d56

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
thanks @ayushkumar2808 for you submission, the self-viva for `DML commands` is satisfactory.

however, you have not added a demo. please consider adding that.

thanks.

**Comment by ayushkumar2808** [comment]
this is the demo with postman testing
https://www.loom.com/share/1186e8084c7942eab95aec055e851bb2?sid=ea22d2ef-d8d8-49d2-814a-b17b181a6b43

**Comment by th3c0d3br34ker** [comment]
thanks @ayushkumar2808 the  submission. i reviewed your self-viva for `this` pointer and `Interface`. The concepts were not explained in detail. For example you could have explained the uses on Interface.

please schedule a viva, the link is available in the wiki.

thanks

**Review by th3c0d3br34ker — APPROVED** [review]
approved during viva.

**Pull request merged**
